# Generated by Django 2.0 on 2017-12-07 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.Choice')),
                ('confidence_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.ConfidenceNumber')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userchoices',
            name='choice_id',
        ),
        migrations.RemoveField(
            model_name='userchoices',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='game',
            name='related_choice',
            field=models.ManyToManyField(blank=True, null=True, to='pool.Choice'),
        ),
        migrations.DeleteModel(
            name='UserChoices',
        ),
    ]
