# Generated by Django 2.0 on 2017-12-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_auto_20171207_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
